{% set version = "1.0.3" %}

package:
  name: flup
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/flup/flup-{{ version }}.tar.gz
  sha256: 5eb09f26eb0751f8380d8ac43d1dfb20e1d42eca0fa45ea9289fa532a79cd159

build:
  number: 1001
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - flup
    - flup.client
    - flup.client.fcgi_app
    - flup.client.scgi_app
    - flup.server
    - flup.server.ajp
    - flup.server.ajp_base
    - flup.server.ajp_fork
    - flup.server.cgi
    - flup.server.fcgi
    - flup.server.fcgi_base
    - flup.server.fcgi_fork
    - flup.server.fcgi_single
    - flup.server.paste_factory
    - flup.server.preforkserver
    - flup.server.scgi
    - flup.server.scgi_base
    - flup.server.scgi_fork
    - flup.server.singleserver
    - flup.server.threadedserver
    - flup.server.threadpool

about:
  home: http://www.saddi.com/software/flup/
  # no license file, no dev URL for submitting a pull
  license: BSD
  license_family: BSD
  summary: 'Random assortment of WSGI servers'

extra:
  recipe-maintainers:
    - pmlandwehr
