{% set name = "flup" %}
{% set version = "1.0.3" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "5eb09f26eb0751f8380d8ac43d1dfb20e1d42eca0fa45ea9289fa532a79cd159" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  skip: True  # [py2k]
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - flup
    - flup.client
    - flup.client.fcgi_app
    - flup.client.scgi_app
    - flup.server
    - flup.server.ajp
    - flup.server.ajp_base
    - flup.server.ajp_fork
    - flup.server.cgi
    - flup.server.fcgi
    - flup.server.fcgi_base
    - flup.server.fcgi_fork
    - flup.server.fcgi_single
    - flup.server.paste_factory
    - flup.server.preforkserver
    - flup.server.scgi
    - flup.server.scgi_base
    - flup.server.scgi_fork
    - flup.server.singleserver
    - flup.server.threadedserver
    - flup.server.threadpool

about:
  home: http://www.saddi.com/software/flup/
  # no license file, no dev URL for submitting a pull
  license: BSD
  license_family: BSD
  summary: 'Random assortment of WSGI servers'

extra:
  recipe-maintainers:
    - pmlandwehr
