travis:
  secure:
    BINSTAR_TOKEN: iM6Tcj+buQ7klU7Bcfl4nXlxtvTHW8qgaj2U00nQRklXmRYgZpAxhqd+OMo3JbiktA9byJ1yTgGjQrrAhHx95tL+yaYXuELlkAJ6QnZ3Itcs2bcRSYhjkp7JmKIynkU3Ev5fkv2r5VwokaKRuGoO1O5tr7vmWQ6S04ThzuvQhNYvqsK9Kor1S6fXs2CB3g2gA19uqCyxKc6Pk3ymnSRAZig5PYBR2a9/XPpZt8NeIRO73yWAJNIsaF/pENeKEcH3v83x1T9Yx2PHPvxWw5K30bniV6gu3ujaIQ8/IsqfacAHwV5JEOM6sKDTTcG/A3H9kIG/G+u6ehVwROvS2BH83pnEEnhB/em/Xa5ffSPLSOExBbjOyu/LOfV7el/X+kEaASBHL1bAQrHG0QufNxycx1t0DTHY1JCtUgUlrX21qwVXoRn925nD756AJaRI1SAOvJKKz6D/myNOYnEParEcoyfh9D7B3F9dM+EBC+7YODth8+TMl+YiI5zTBVX/aq92pwIgaJaFvjoLOKVlEwaLdwrm6dtSFO+oMcNe4Od8Svs2Rt8u+BheuJVd1vHgIv+EJUmWEkKgqkwv8gpMX6syN660d6SUAvFFQJ5VxsVkcIveOc/fuibJVLrbKvDMdx75nPY7w4KKwPxqEnkBZP2FeDL0hZ0QhLLrU81tZLyD+tw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
