travis:
  secure:
    BINSTAR_TOKEN: ftiDFy82SVj8QV6UZ6+lIoNHMOvJJONMTPCvTPnS1VpSey5XPaxRqLkyEKDmUeIwW6yt5p3ivTzox432JN0eY43YMEhaK1Y+pJA0FZaoC/RPLJtB4eW7wozBaonlep3H9f8kXK2NkEGPDI8I4yXm9IknceKfafblreGyNvx2RIWk3zqEMnkWaCQpNLKe/91uSQGr/BN6qFDI5Zl3iXdcEaCqJgBD7+5cm4zCmZLxY5DaN1WUbMndF12yF7eEu5N4gLgnDufuDBdpDhjPyD1yFRY9MzM6E/B/WprzTJ1ai+E7e9Oc0u8Rfe2//PWtoVrGlSOuGTZmzO+l3i5pufFC0oGTFSHltsx7hP8K9IE6pEJId3/gaDEZuMY0fuSTKff8YFWVH4AKLNZ+BlrSoJHWuJ3rD1HThUhVD5gUKF57QmfM7DlSM41vodr/hPeAEOOSJWrgbNGoOye9o0JCPEY9BlLWx4JSGdsBEOj7phBkc4fYT0xirI7lnyVfR6Uic1tJWlsNtdZGpppbd98Mc65qtRnF+dsWb1uA03kItzBR3oy2VsQpT8fXW4QJHnn3TIeD7X9Uew5yyHznnu80A6guS2y0ovy1p7QzNFacqUZEM7EV0jn0N+gSQnfAubBaTH9Mn+fqDY6GPEDdsudaiWkWJtDnMY8SX6CuygP3mhI/s3E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
